config/routes.rb
Rails.application.routes.draw do

  # Generated by jumaccount_generator 1.0.0 Start (vor resources :profiles!)
  get 'users/profiles/edit'   => 'profiles#useredit', :as => 'edit_user_profile'
  get 'users/profiles/quit'   => 'profiles#quit', :as => 'quit_user_profile'

  get   'users/:user_id/rights' => 'rights#userindex',  :as => 'user_rights'
  post  'users/:user_id/rights' => 'rights#usercreate',  :as => 'create_user_right'
  get   'users/:user_id/rights/new' => 'rights#usernew',  :as => 'new_user_right'
  get   'users/:user_id/rights/:id/edit' => 'rights#useredit',  :as => 'edit_user_right'
  get   'users/:user_id/rights/:id' => 'rights#usershow',  :as => 'user_right'
  patch 'users/:user_id/rights/:id' => 'rights#userupdate'
  put   'users/:user_id/rights/:id' => 'rights#userupdate'
  delete 'users/:user_id/rights/:id' => 'rights#userdestroy'
  get   'users/:user_id/rights/:id/choose' => 'rights#userchoose',  :as => 'choose_user_right'
  # Generated by jumaccount_generator 1.0.0 Ende

  resources :profiles

  resources :rights

  resources :teams

  resources :companies

  resources :discs

  root to: 'visitors#index'
  devise_for :users
  resources :users
  
end

app/models/company.rb
# # Generated by jumaccount_generator 1.0.0
class Company < ActiveRecord::Base
  validates  :company_name, presence: true, uniqueness: true
end

app/controllers/companies_controller.rb
# # Generated by jumaccount_generator 1.0.0
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
    authorize Company
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    authorize @company
  end

  # GET /companies/new
  def new
    @company = Company.new
    authorize @company
  end

  # GET /companies/1/edit
  def edit
    authorize @company
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    authorize @company

    respond_to do |format|
      if @company.save
        format.html { redirect_to companies_url, notice: "Company: #{I18n.t('helpers.saved')}" }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    authorize @company
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to companies_url, notice: "Company: #{I18n.t('helpers.saved')}" }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    authorize @company
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company: #{I18n.t('helpers.deleted')}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:company_name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> <%= I18n.t('helpers.saveerror') %></h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </div>

  <div class="actions">
    <%# = f.submit %>
    <p><br/>
    <% if ( params[:action] == 'show' ) %>
      <%= link_to companies_path, :class => "btn btn-primary btn-xs" do %>
        <% t('helpers.cancel') %>
      <% end %>
    <% else %>    <%= link_to companies_path, :class => "btn btn-default btn-xs" do %>
        <% t('helpers.cancel') %>
      <% end %>
      <button type="submit" class="btn btn-success btn-xs submit">Company <%= t('helpers.save') %></button>
    <% end %>  </p>
  </div>

<% end %>

app/views/companies/edit.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<h1>Edit Company</h1>

<%= render 'form' %>

app/views/companies/index.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<div class="container">
	<div class="row">
		<h3>Companies</h3>
		<div class="column">
			
			<table class="table">
				<thead>
					<tr>
						<th>Company name</th>
						<th colspan="3">Actions</th>
					</tr>
				</thead>

				<tbody>
					<% @companies.each do |company| %>
					<tr>
						<td><%= company.company_name %></td>
						<td><%= link_to 'Show', company %></td>
						<td><%= link_to 'Edit', edit_company_path(company) %></td>
						<td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
					<% end %>
				</tbody>
			</table>

			<br>

			<%= link_to 'New Company', new_company_path %>
		</div>
	</div>
</div>

app/views/companies/new.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<h3>New Company</h3>

<%= render 'form' %>

app/views/companies/show.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<h3>Show Company</h3>

<p>
  <strong>Company name:</strong>
  <%= @company.company_name %>
</p>

<%= link_to edit_company_path(@company), :class => "btn btn-default btn-xs" do %>
        <% t('helpers.edit') %>
<% end %>&nbsp;
<%= link_to companies_path, :class => "btn btn-primary btn-xs" do %>
        <% t('helpers.back') %>
<% end %>