config/routes.rb
Rails.application.routes.draw do

  # Generated by jumaccount_generator 1.0.0 Start (vor resources :profiles!)
  get 'users/profiles/edit'   => 'profiles#useredit', :as => 'edit_user_profile'
  get 'users/profiles/quit'   => 'profiles#quit', :as => 'quit_user_profile'

  get   'users/:user_id/rights' => 'rights#userindex',  :as => 'user_rights'
  post  'users/:user_id/rights' => 'rights#usercreate',  :as => 'create_user_right'
  get   'users/:user_id/rights/new' => 'rights#usernew',  :as => 'new_user_right'
  get   'users/:user_id/rights/:id/edit' => 'rights#useredit',  :as => 'edit_user_right'
  get   'users/:user_id/rights/:id' => 'rights#usershow',  :as => 'user_right'
  patch 'users/:user_id/rights/:id' => 'rights#userupdate'
  put   'users/:user_id/rights/:id' => 'rights#userupdate'
  delete 'users/:user_id/rights/:id' => 'rights#userdestroy'
  get   'users/:user_id/rights/:id/choose' => 'rights#userchoose',  :as => 'choose_user_right'
  # Generated by jumaccount_generator 1.0.0 Ende

  resources :profiles

  resources :rights

  resources :teams

  resources :companies

  resources :discs

  root to: 'visitors#index'
  devise_for :users
  resources :users
  
end

app/models/right.rb
# # Generated by jumaccount_generator 1.0.0
class Right < ActiveRecord::Base
  belongs_to :user
  belongs_to :company
  belongs_to :team
  
  # example role names, please adopt
  enum right_role: {no_rights: 0,
                    employee: 1, 
                    external: 2,
                    manager: 3,
                    team_coach: 4 ,
                    team_master: 5
                 }

  after_initialize :init, :if => :new_record?
  validates  :user_id, presence: true
  validates  :company_id, presence: true
  validates  :team_id, presence: true

  def init
    if self.new_record?
      self.right_role ||= :no_rights
      # conflicts with validates:
      # self.user_id ||= 0
      # self.company_id ||= 0
      # self.team_id ||= 0
    end
  end


end

app/controllers/rights_controller.rb
# # Generated by jumaccount_generator 1.0.0
class RightsController < ApplicationController
  helper ApplicationHelper

  before_action :set_right, only: [:show, :edit, :update, :destroy, 
                                   :usershow, :useredit, :userupdate, :userdestroy]
  before_action :set_actuser, only: [:usershow, :useredit, :userupdate, :userdestroy, 
                                     :userindex, :usercreate, :usernew, :userchoose]
  
  # GET /rights
  # GET /rights.json
  def index
    @rights = Right.all
  end

  # GET /users/1/rights
  def userindex
    @rights = Right.where(user_id: @actuser)
    render :userindex
  end

  # GET /rights/1
  # GET /rights/1.json
  def show
  end
  # GET /users/1/rights/1
  # GET /users/1/rights/1.json
  def usershow
    render :usershow
  end

  # GET /users/user_id/rights/new
  def usernew
    @right = Right.new
    @right.user_id = @actuser.id
    render :usernew
  end

  # GET /rights/new
  def new
   @right = Right.new
  end

  # GET /rights/1/useredit
  def useredit
    authorize @right
    render :useredit
  end
  
  # GET /rights/1/edit
  def edit
  end

  # GET /users/user_id/rights/1/edit
  def userchoose
    @actuser = User.find(params[:user_id])
    @right = Right.find(params[:id])
    authorize @right
    session[:current_right] = @right
    redirect_to (request.referrer || root_path) # Send them back to them page they came from, or to the root page.
  end

  # POST /rights
  # POST /rights.json
  def usercreate
    @right = Right.new(right_params)

    respond_to do |format|
      if @right.save
        format.html { redirect_to user_rights_path(@actuser), notice: "Right: #{I18n.t('helpers.saved')}" }
        format.json { render :show, status: :created, location: @right }
      else
        format.html { render :usernew }
        format.json { render json: @right.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /rights
  # POST /rights.json
  def create
    @right = Right.new(right_params)

    respond_to do |format|
      if @right.save
        format.html { redirect_to rights_url, notice: "Right: #{I18n.t('helpers.saved')}" }
        format.json { render :show, status: :created, location: @right }
      else
        format.html { render :new }
        format.json { render json: @right.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1/rights/1
  # PATCH/PUT /users/1/rights/1.json
  def userupdate
    respond_to do |format|
      if @right.update(right_params)
        format.html { redirect_to user_rights_path(@actuser), notice: "Right: #{I18n.t('helpers.saved')}" }
        format.json { render :show, status: :ok, location: @right }
      else
        format.html { render :useredit }
        format.json { render json: @right.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rights/1
  # PATCH/PUT /rights/1.json
  def update
    respond_to do |format|
      if @right.update(right_params)
        format.html { redirect_to rights_url, notice: "Right: #{I18n.t('helpers.saved')}" }
        format.json { render :show, status: :ok, location: @right }
      else
        format.html { render :edit }
        format.json { render json: @right.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1/rights/1
  # DELETE /users/1/rights/1.json
  def userdestroy
    @right.destroy
    respond_to do |format|
      format.html { redirect_to user_rights_path(@actuser), notice: "Right: #{I18n.t('helpers.deleted')}" }
      format.json { head :no_content }
    end
  end
  
  # DELETE /rights/1
  # DELETE /rights/1.json
  def destroy
    @right.destroy
    respond_to do |format|
      format.html { redirect_to rights_url, notice: "Right: #{I18n.t('helpers.deleted')}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_right
      @right = Right.find(params[:id])
    end
    def set_actuser
      @actuser = User.find(params[:user_id])
    end
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def right_params
      params.require(:right).permit(:right_role, :user_id, :company_id, :team_id)
    end
end

app/helpers/rights_helper.rb
# # Generated by jumaccount_generator 1.0.0
module RightsHelper
  
  def right_company_id_select
    x = []
    Company.find_each do |c|
      x.push(["#{c.company_name}", c.id])
    end
    return x
  end
  
  def right_team_id_select
    x = []
    Team.find_each do |t|
      x.push(["#{t.team_name}", t.id])
    end
    return x
  end

  def right_user_id_select
    x = []
    User.find_each do |u|
      x.push(["#{u.email}", u.id])
    end
    return x
  end

end

app/views/rights/_form.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<%= form_for(@right) do |f| %>
  <%= render 'form_errors', f: @right %>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select :user_id, right_user_id_select, {:include_blank => true } %>
  </div>
  <%= render 'form_fields', f: f %>
  <div class="actions">
    <%# = f.submit %>
    <p><br/>
    <% if ( params[:action] == 'show' ) %>
      <%= link_to rights_path, :class => "btn btn-primary btn-xs" do %>
        <% t('helpers.cancel') %>
      <% end %>
    <% else %>    <%= link_to rights_path, :class => "btn btn-default btn-xs" do %>
        <% t('helpers.cancel') %>
      <% end %>
      <button type="submit" class="btn btn-success btn-xs submit">Right <%= t('helpers.save') %></button>
    <% end %>  </p>
  </div>

<% end %>

app/views/rights/_form_errors.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
  <% if f.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(f.errors.count, "error") %> <%= I18n.t('helpers.saveerror') %></h2>

      <ul>
      <% f.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/rights/_form_fields.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
  <div class="field">
    <%= f.label :company_id %><br>
    <%# = f.text_field :company_id %>
    <%= f.select :company_id, right_company_id_select, {:include_blank => true } %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br>
    <%# = f.text_field :team_id %>
    <%= f.select :team_id, right_team_id_select, {:include_blank => true } %>

  </div>
  <div class="field">
    <%= f.label :right_role %><br>
    <%= f.select(:right_role, Right.right_roles.keys.map {|role| [role.titleize,role]}) %>  
  </div>

app/views/rights/_right.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
            <td><%= right.company.company_name %></td>
            <td><%= right.company_id %></td>
            <td><%= right.team.team_name %></td>
            <td><%= right.team_id %></td>
            <td><%= right.user.email %></td>
            <td><%= right.user_id %></td>
            <td><%= right.right_role.titleize %></td>
            <td><%= link_to 'Show', right %></td>
            <td><%= link_to 'Edit', edit_right_path(right) %></td>
            <td><%= link_to 'Destroy', right, method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/rights/_userform.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<%= form_for([@actuser, @right]) do |f| %>
  <%= render 'form_errors', f: @right %>
  <%= f.hidden_field :user_id, :value => @actuser.id %>
  <%= render 'form_fields', f: f %>
  <div class="actions">
    <%# = f.submit %>
    <p><br/>
    <% if ( params[:action] == 'show' ) %>
      <%= link_to user_rights_path(@actuser), :class => "btn btn-primary btn-xs" do %>
        <% t('helpers.cancel') %>
      <% end %>
    <% else %>    <%= link_to user_rights_path(@actuser), :class => "btn btn-default btn-xs" do %>
        <% t('helpers.cancel') %>
      <% end %>
      <button type="submit" class="btn btn-success btn-xs submit">Right <%= t('helpers.save') %></button>
    <% end %>  </p>
  </div>
<% end %>

app/views/rights/edit.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<h3>Edit Right</h3>

<%= render 'form' %>

app/views/rights/index.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<div class="container">
  <div class="row">
    <h3>Rights</h3>
    <div class="column">

      <table class="table">
        <thead>
          <tr>
            <th>Company</th>
            <th>ID</th>
            <th>Team</th>
            <th>ID</th>
            <th>User</th>
            <th>ID</th>
            <th>Right role</th>
            <th colspan="2">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @rights.each do |right| %>
          <tr>
            <td><%= right.company.company_name %></td>
            <td><%= right.company_id %></td>
            <td><%= right.team.team_name %></td>
            <td><%= right.team_id %></td>
            <td><%= right.user.email %></td>
            <td><%= right.user_id %></td>
            <td><%= right.right_role.titleize %></td>
            <td><%= link_to 'Edit', edit_right_path(right) %></td>
            <td><%= link_to 'Destroy', right, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Right', new_right_path %>
    </div>
  </div>
</div>

app/views/rights/new.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<h3>New Right</h3>

<%= render 'form' %>

app/views/rights/show.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<h3>Showing Right</h3>

<p>
  <strong>Right role:</strong>
  <%= @right.right_role %>
</p>

<p>
  <strong>User:</strong>
  <%= "#{@right.user.user_account_name} - #{@right.user.email}" %>
</p>

<p>
  <strong>Company:</strong>
  <%= @right.company.company_name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @right.team.team_name %>
</p>

<%= link_to 'Edit', edit_right_path(@right) %> |
<%= link_to 'Back', rights_path %>

app/views/rights/useredit.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<h3>Editing Right <%= @actuser.user_account_name %> - <%= @actuser.email %></h3>

<%= render 'userform' %>

app/views/rights/userindex.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<div class="container">
  <div class="row">
    <h3>Rights <%= @actuser.user_account_name %> - <%= @actuser.email %></h3>
    <div class="column">

      <table class="table">
        <thead>
          <tr>
            <th>Company</th>
            <th>ID</th>
            <th>Team</th>
            <th>ID</th>
            <th>Right role</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>


        <tbody>
          <% @rights.each do |right| %>
          <tr>
            <td><%= right.company.company_name %></td>
            <td><%= right.company_id %></td>
            <td><%= right.team.team_name %></td>
            <td><%= right.team_id %></td>
            <td><%= right.right_role.titleize %></td>
            <td><%= link_to 'Show', user_right_path(@actuser.id, right) %></td>
            <td><%= link_to 'Edit', edit_user_right_path(@actuser.id, right) %></td>
            <td><%= link_to 'Destroy', user_right_path(@actuser.id, right), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to "New Right for #{@actuser.email}", new_user_right_path(@actuser.id) %>
    </div>
  </div>
</div>

app/views/rights/usernew.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<h3>New Right <%= @actuser.user_account_name %> - <%= @actuser.email %></h3>

<%= render 'userform' %>

app/views/rights/usershow.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>
<h3>Showing Right <%= @actuser.user_account_name %> - <%= @actuser.email %></h3>

<p>
  <strong>Right role:</strong>
  <%= @right.right_role %>
</p>

<p>
  <strong>User:</strong>
  <%= "#{@right.user.user_account_name} - #{@right.user.email}" %>
</p>

<p>
  <strong>Company:</strong>
  <%= @right.company.company_name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @right.team.team_name %>
</p>

<%= link_to edit_user_right_path( @actuser, @right ), :class => "btn btn-default btn-xs" do %>
        <% t('helpers.edit') %>
<% end %>&nbsp;
<%= link_to user_rights_path(@actuser), :class => "btn btn-primary btn-xs" do %>
        <% t('helpers.back') %>
<% end %>