config/routes.rb
Rails.application.routes.draw do

  # Generated by jumaccount_generator 1.0.0 Start (vor resources :profiles!)
  get 'users/profiles/edit'   => 'profiles#useredit', :as => 'edit_user_profile'
  get 'users/profiles/quit'   => 'profiles#quit', :as => 'quit_user_profile'

  get   'users/:user_id/rights' => 'rights#userindex',  :as => 'user_rights'
  post  'users/:user_id/rights' => 'rights#usercreate',  :as => 'create_user_right'
  get   'users/:user_id/rights/new' => 'rights#usernew',  :as => 'new_user_right'
  get   'users/:user_id/rights/:id/edit' => 'rights#useredit',  :as => 'edit_user_right'
  get   'users/:user_id/rights/:id' => 'rights#usershow',  :as => 'user_right'
  patch 'users/:user_id/rights/:id' => 'rights#userupdate'
  put   'users/:user_id/rights/:id' => 'rights#userupdate'
  delete 'users/:user_id/rights/:id' => 'rights#userdestroy'
  get   'users/:user_id/rights/:id/choose' => 'rights#userchoose',  :as => 'choose_user_right'
  # Generated by jumaccount_generator 1.0.0 Ende

  resources :profiles

  resources :rights

  resources :teams

  resources :companies

  resources :discs

  root to: 'visitors#index'
  devise_for :users
  resources :users
  
end

app/models/disc.rb
class Disc < ActiveRecord::Base
  # Generated by jumaccount_generator 1.0.0 Start
  belongs_to :user
  belongs_to :company
  belongs_to :team

  validates  :user_id, presence: true
  validates  :company_id, presence: true
  validates  :team_id, presence: true

  def set_admission(right)
    self.user_id    = right.user_id
    self.company_id = right.company_id
    self.team_id    = right.team_id
    return self
  end
  # End of generator insertion

  after_initialize :init, :if => :new_record?
  
  def init
    if self.new_record?
      self.feld1 ||= ""
      self.feld1 ||= ""
      self.tracks ||= 0
    end
  end

end

app/controllers/discs_controller.rb
class DiscsController < ApplicationController
  before_filter :authenticate_user! # jumadmission generator
  after_action :verify_authorized, :except => :index # jumadmission generator
  after_action :verify_policy_scoped, :only => :index # jumadmission generator
  before_action :set_disc, only: [:show, :edit, :update, :destroy]

  # GET /discs
  # GET /discs.json
  def index
    @discs = policy_scope(Disc) # jumadmission generator index
 #     @discs = Disc.all
  end

  # GET /discs/1
  # GET /discs/1.json
  def show
    authorize @disc # jumadmission generator show
  end

  # GET /discs/new
  def new
    @disc = Disc.new
    authorize @disc # jumadmission generator new
  end

  # GET /discs/1/edit
  def edit
    authorize @disc # jumadmission generator edit
  end

  # POST /discs
  # POST /discs.json
  def create
    @disc = Disc.new(disc_params).set_admission(current_right) # jumadmission generator: set_admission
    authorize @disc # jumadmission generator create

    respond_to do |format|
      if @disc.save
        format.html { redirect_to action: :index, notice: "Disc: #{I18n.t('helpers.saved')}" }
        format.json { render :show, status: :created, location: @disc }
      else
        format.html { render :new }
        format.json { render json: @disc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discs/1
  # PATCH/PUT /discs/1.json
  def update
    authorize @disc # jumadmission generator update
    respond_to do |format|
      if @disc.update(disc_params)
        format.html { redirect_to action: :index, notice: "Disc: #{I18n.t('helpers.saved')}" }
        format.json { render :show, status: :ok, location: @disc }
      else
        format.html { render :edit }
        format.json { render json: @disc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discs/1
  # DELETE /discs/1.json
  def destroy
    authorize @disc # jumadmission generator destroy
    @disc.destroy
    respond_to do |format|
      format.html { redirect_to discs_url, notice: "Disc: #{I18n.t('helpers.deleted')}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disc
      @disc = Disc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disc_params
      params.require(:disc).permit(:feld1, :feld2, :tracks, :user_id, :company_id, :team_id)
    end
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/views/discs/_form.html.erb
<%= form_for(@disc) do |f| %>
  <% if @disc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disc.errors.count, "error") %> <%= I18n.t('helpers.saveerror') %></h2>

      <ul>
      <% @disc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, :value => @disc.user_id %>
  <%= f.hidden_field :company_id, :value => @disc.company_id %>
  <%= f.hidden_field :team_id, :value => @disc.team_id %>

  <div class="field">
    <%= f.label :feld1 %><br>
    <%= f.text_field :feld1 %>
  </div>
  <div class="field">
    <%= f.label :feld2 %><br>
    <%= f.text_field :feld2 %>
  </div>
  <div class="field">
    <%= f.label :tracks %><br>
    <%= f.number_field :tracks %>
  </div>
  <div class="actions">
    <%# = f.submit %>
    <p><br/>
    <% if ( params[:action] == 'show' ) %>
      <%= link_to discs_path, :class => "btn btn-primary btn-xs" do %>
        <% t('helpers.cancel') %>
      <% end %>
    <% else %>    <%= link_to discs_path, :class => "btn btn-default btn-xs" do %>
        <% t('helpers.cancel') %>
      <% end %>
      <button type="submit" class="btn btn-success btn-xs submit">Disc <%= t('helpers.save') %></button>
    <% end %>  </p>
  </div>
<% end %>

app/views/discs/edit.html.erb
<h1>Edit Disc</h1>

<%= render 'form' %>

app/views/discs/index.html.erb
<div class="container">
	<div class="row">
		<h3>Discs</h3>
		<div class="column">

			<table class="table">
				<thead>
					<tr>
						<th>Feld1</th>
						<th>Feld2</th>
						<th>Tracks</th>
						<th>User_Id</th>
						<th>Company_Id</th>
						<th>Team_Id</th>
						<th colspan="3">Actions</th>
					</tr>
				</thead>

				<tbody>
					<% @discs.each do |disc| %>
					<tr>
						<td><%= disc.feld1 %></td>
						<td><%= disc.feld2 %></td>
						<td><%= disc.tracks %></td>
						<td><%= disc.user_id %></td>
						<td><%= disc.company_id %></td>
						<td><%= disc.team_id %></td>
						<td><%= link_to 'Show', disc %></td>
						<td><%= link_to 'Edit', edit_disc_path(disc) %></td>
						<td><%= link_to 'Destroy', disc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
					<% end %>
				</tbody>
			</table>

			<br>

			<%= link_to 'New Disc', new_disc_path %>
		</div>
	</div>
</div>

app/views/discs/new.html.erb
<h1>New Disc</h1>

<%= render 'form' %>

app/views/discs/show.html.erb
<h3>Show Team</h3>

<p>
  <strong>Feld1:</strong>
  <%= @disc.feld1 %>
</p>

<p>
  <strong>Feld2:</strong>
  <%= @disc.feld2 %>
</p>

<p>
  <strong>Tracks:</strong>
  <%= @disc.tracks %>
</p>

<%= link_to edit_disc_path(@disc), :class => "btn btn-default btn-xs" do %>
        <% t('helpers.edit') %>
<% end %>&nbsp;
<%= link_to discs_path, :class => "btn btn-primary btn-xs" do %>
        <% t('helpers.back') %>
<% end %>