config/routes.rb
Rails.application.routes.draw do

  # Generated by jumaccount_generator 1.0.0 Start (vor resources :profiles!)
  get 'users/profiles/edit'   => 'profiles#useredit', :as => 'edit_user_profile'
  get 'users/profiles/quit'   => 'profiles#quit', :as => 'quit_user_profile'

  get   'users/:user_id/rights' => 'rights#userindex',  :as => 'user_rights'
  post  'users/:user_id/rights' => 'rights#usercreate',  :as => 'create_user_right'
  get   'users/:user_id/rights/new' => 'rights#usernew',  :as => 'new_user_right'
  get   'users/:user_id/rights/:id/edit' => 'rights#useredit',  :as => 'edit_user_right'
  get   'users/:user_id/rights/:id' => 'rights#usershow',  :as => 'user_right'
  patch 'users/:user_id/rights/:id' => 'rights#userupdate'
  put   'users/:user_id/rights/:id' => 'rights#userupdate'
  delete 'users/:user_id/rights/:id' => 'rights#userdestroy'
  get   'users/:user_id/rights/:id/choose' => 'rights#userchoose',  :as => 'choose_user_right'
  # Generated by jumaccount_generator 1.0.0 Ende

  resources :profiles

  resources :rights

  resources :teams

  resources :companies

  resources :discs

  root to: 'visitors#index'
  devise_for :users
  resources :users
  
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_accounting' %>
      <%= link_to 'Discs', discs_path, class: 'navbar-brand' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_accounting.html.erb
<%# Generated by jumaccount_generator 1.0.0 %>

<%# add navigation links to this file %>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= I18n.t('usermenu.menu')%><span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <% if user_signed_in? %>
      <li role="presentation"><%= link_to I18n.t('usermenu.sign_out'), destroy_user_session_path, :method=>'delete' %></li>
      <li class="divider"></li>
      <li role="presentation" class="dropdown-header"><%= I18n.t('usermenu.roles')%></li>
            <% if (session[:current_right] == nil)
            	puts "session right nil"
            end
            if (session[:current_user] == nil)
              	puts "session user nil"
            end %>
      <%# find_by_id doesnt throw error, if profile_preferred_right_id is not set %>
      <% if ((session[:current_right] == nil) && !(current_user.profile == nil))
        	 session[:current_right] = Right.find_by_id(current_user.profile.profile_preferred_right_id)
         end %>
      <% current_user.rights.each do |r| %>
        <% if (session[:current_right] == nil)
        	 session[:current_right] = r
           end %>
        <% puts "=== current_right id = #{session[:current_right]['id']}" %>
        <% puts "=== r.id = #{r.id}" %>
        <% if ( session[:current_right]['id'] == r.id) %>
          <li role="presentation" class="active"><%= link_to "#{r.team.team_name} - #{r.right_role.titleize}", choose_user_right_path(current_user,r), html_options = {role: "menuitem", tabindex: "-1"} %></li>
        <% else %>
          <li role="presentation"><%= link_to "#{r.team.team_name} - #{r.right_role.titleize}", choose_user_right_path(current_user,r), html_options = {role: "menuitem", tabindex: "-1"} %></li>
        <% end %>
      <% end %>
      <li class="divider"></li>
        <li role="presentation" class="dropdown-header"><%= I18n.t('usermenu.preferences')%></li>
      <li role="presentation"><%= link_to I18n.t('usermenu.edit_account'), edit_user_registration_path %></li>
      <li role="presentation"><%= link_to I18n.t('usermenu.edit_profile'), edit_user_profile_path %></li>
    <% else %><%# not signed in %>
      <li role="presentation"><%= link_to I18n.t('usermenu.sign_in'), new_user_session_path %></li>
      <li role="presentation"><%= link_to I18n.t('usermenu.sign_up'), new_user_registration_path %></li>
    <% end %><%# if user_signed_in? %>
    <% if user_signed_in? %>
      <% if current_user.admin? %>
        <li class="divider"></li>
        <li role="presentation" class="dropdown-header"><%= I18n.t('usermenu.administration')%></li>
        <li role="presentation"><%= link_to I18n.t('usermenu.users'),     users_path     %></li>
        <li role="presentation"><%= link_to I18n.t('usermenu.rights'),    rights_path    %></li>
        <li role="presentation"><%= link_to I18n.t('usermenu.profiles'),  profiles_path  %></li>
        <li role="presentation"><%= link_to I18n.t('usermenu.teams'),     teams_path     %></li>
        <li role="presentation"><%= link_to I18n.t('usermenu.companies'), companies_path %></li>
      <% end %>
    <% end %>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise Pundit" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Pundit" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>